### ISSUE TITLE
NoteSongAPI Help Wanted!

### ISSUE THREAD

**Issue by File14** [if-Team/Nukkit-Plugins#1]
Hello!

How do I get all NoteBlockSongs? How do I play one? How can I play another song when the first song has ended? How can I stop the song? Where do I put the songs, what folder? Is the songs NBS files?

Thanks!

**Comment by OverTook** [comment]
@File14

It provides only API.

**Comment by File14** [comment]
Yes but how to play a song via the API? :D @OverTook

**Comment by File14** [comment]
Please @DeBe0 tell me how to add a song from a folder(NBS file) and then play it to a player!

**Comment by 110EIm** [comment]
You can decode music file(binary) into NoteSong instance using  BaseDecoder.
After that, you can play songs by registering NoteSong instance you decoded using API in the class: NoteSongAPI
